# Generated by Django 2.0.2 on 2018-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NICKNAME', models.CharField(max_length=20)),
                ('COMMENT', models.CharField(max_length=300)),
                ('DATE', models.DateField()),
            ],
        ),
    ]
