version: '3'

services:
  backend:
    build: .:/backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  frontend:
    build: .:/frontend
    ports:
      - "5000:5000"
    depends_on:
      -backend
